### ISSUE TITLE
Version 2.0.0: Testing and Feedback

### ISSUE THREAD

**Issue by fnagel** [fnagel/t3extblog#79]
Version 2.0 with TYPO3 7.x support and Twitter Bootstrap 3 theme is just around the corner.

What's missing is some more testing and feedback on what needs to be improved! Please help and test the latest master branch!

**What needs to be tested:**

* Creating log posts (with and without preview image and text)
* Posting comments and subscribe for new comments
* Using the subscription manager (confirm and delete)
* Email sending: admin, subscriber opt-in and notification
* Email sending triggered by: Frontend & Backend (confirm and un-spam a comment)

Testing needed for TYPO3 CMS 6.2.x and 7.4.x on a multi-language installation.

**Comment by fnagel** [comment]
@criwe @pvanhemmen

**Comment by pvanhemmen** [comment]
Will test extensively on both versions within next days and report back.

**Comment by criwe** [comment]
I´ve started testing, 2 things:
1.) If the TS (storagePid, blogsystemPid) is not put in the rootpage, the BE-Module throws an error (see screenshot), while everything else (FE Output etc.) works fine.
![be_modul](https://cloud.githubusercontent.com/assets/7531138/9342994/71993b4c-45ff-11e5-81fc-453a0ad2cdd6.png)

2.) When writing a comment on a non-default-language page, the acknowledgment is shown on the default-language-page. This behavior is independent from any settings (i.e. appove comment by default)

Tested: TYPO3 6.2.14, Bootstrappackage (local installation via bitnami)

**Comment by pvanhemmen** [comment]
First feedback after testing in 7.4.0
1.) Dependency is still set to 7.3.99 and gives a warning when installing t3extblog
2.) Editing comments in the BE is not possible with 7.x
![comment_edit](https://cloud.githubusercontent.com/assets/715022/9350172/6c1a61c4-464e-11e5-97c2-04518fa762e2.png)
3.) With standard settings the valid time of the subscription link is 03.01.1970 - 01:00:00 Server time is set correctly.
4.) Pagination of posts seems to have slipped out of place again in the BE in 7.4.x
![pagination](https://cloud.githubusercontent.com/assets/715022/9350230/16039e12-464f-11e5-966d-f6d52b80260e.png)

**Comment by fnagel** [comment]
@criwe 

> the BE-Module throws an error

Error is fired within our BE controller as no TS was found. Seems this is related to this TS snippet: https://github.com/fnagel/t3extblog/blob/master/ext_typoscript_setup.txt#L114-L122

Would you mind trying to move this code snippet behind the default static TS setup?


> the acknowledgment is shown on the default-language-page

What does this mean? The comment created flash message? So when creating a blogpost for DE the flash message is shown on the same blogpost but the EN version?

**Comment by fnagel** [comment]
@pvanhemmen I sware I've tested this in 7.3.x and I knew why I not raised the depedency yet :-D
I will take a look asap.

Regarding issue 2): are you aware this is a backward-compatible TCA change?

**Comment by pvanhemmen** [comment]
New wizard registration was introduced in 6.2 and the use of `browse_links.php` was marked as deprecated, so the new registration most probably won't work in versions before 6.2: https://wiki.typo3.org/TYPO3_CMS_6.2 (at bottom of page, see "Adapting to removed typo3/browse_links.php").

**Comment by fnagel** [comment]
> Pagination of posts seems to have slipped out of place again in the BE in 7.4.x

Looks good for me:
![screenshot-1](https://cloud.githubusercontent.com/assets/116824/9354581/d92549d2-4671-11e5-8fbd-1eb8d1bf9d5b.png)

**Comment by fnagel** [comment]
> Editing comments in the BE is not possible with 7.x

Same here, works as expected:
![screenshot-2](https://cloud.githubusercontent.com/assets/116824/9354621/410386fe-4672-11e5-89d2-fd9a6ebacd27.png)

Any chance this is caching issue (due to changing branches or something)?

**Comment by pvanhemmen** [comment]
Editing Posts (your screenhot above) works well. If you change the view to "comments" and try to edit them from the t3extblog Manager, then the rror occurs:
![comments-2](https://cloud.githubusercontent.com/assets/715022/9354716/0dbd5544-4673-11e5-8acc-07cd68940508.png)

**Comment by pvanhemmen** [comment]
Have you installed the bootstrap package? This may explain the pagination problem, as there may be some additional CCS loaded in the backend that I am missing? Just a guess though.

**Comment by fnagel** [comment]
Thanks for the hint, tested post view :-/

Works nice after applying the fix. Should be ok as we only support >= 6.2

> Is there need for a wizard here?
Not sure, but I would go with using what we had.

**Comment by fnagel** [comment]
> Have you installed any predefined package? 

I'm using the bootstrap package (official) but I've checked the BE, there are no additional styles. Here's a screen of the frame only, with source. Latest stable Chrome on Win 8.1

![screenshot-3 png](https://cloud.githubusercontent.com/assets/116824/9358253/541212ba-468b-11e5-9eb8-f8f7fcc04ca6.png)

**Comment by fnagel** [comment]
Update regarding blank pages: historyRecords of DataHandler class is now protected. That's an issue as we need to check if the record has changed with the current edit.

**Comment by fnagel** [comment]
Fixed RTE wizard and BE hook (changing record in BE) in master.

**Comment by pvanhemmen** [comment]
The pagination problem is caused by different CSS files inserted in the BE by TYPO3 running in debug or live mode (Configuration presets).

Your screenshot should be TYPO3 in Debug mode. This is the CSS in Live mode:
![live](https://cloud.githubusercontent.com/assets/715022/9367168/0bce9b5a-46bc-11e5-82aa-8d39faf4deaf.png)

In live mode there are different rules in place that overwrite the pagination style:
![rules](https://cloud.githubusercontent.com/assets/715022/9367207/3a93e35a-46bc-11e5-9d62-c7b53c280280.png)

Is that reproducable?

**Comment by fnagel** [comment]
> With standard settings the valid time of the subscription link is 03.01.1970 - 01:00:00 Server time is set correctly.

Confirmed. Seems related to this change: https://github.com/TYPO3/TYPO3.CMS/commit/cd7647525af0527c7f4f99a27abc25770901e516

They introduced a base parameter. Even if I could make it work with it we would have to add another template for 6.2 -- so I just moved the calculation and added a validUntil variable. That seems to work nice. 

Anyway, we got another problem. Emails triggered in BE does not contain links. It seems the link generation (already hijacked to work in BE in 6.2) is totally broken in 7.4 (but worked in 7.3).

**Comment by fnagel** [comment]
> The pagination problem is caused by different CSS files inserted in the BE by TYPO3 running in debug or live mode.

Got it. Fixed and pushed.

**Comment by pvanhemmen** [comment]
Here's another one:
![divrule](https://cloud.githubusercontent.com/assets/715022/9368717/36366ee6-46c5-11e5-95ed-dce654dd0d21.png)

Happens when trying to edit a subscriber record in list view. Adding a label on line 68 in the TCA of Subscriber.php fixes this.

**Comment by pvanhemmen** [comment]
> Anyway, we got another problem. Emails triggered in BE does not contain links. It seems the link generation (already hijacked to work in BE in 6.2) is totally broken in 7.4 (but worked in 7.3).

Cannot reproduce this. Double checked with emptied cache and all. Emails get sent correctly with the right subscription link. Maybe the subscription manager pid is not set in your typoscript setup? Sorry for asking the most trivial question to you as the extension owner, just remember my initial test where I had the same issue ;-)

**Comment by fnagel** [comment]
No, no, you're almost right. And @criwe is right. TS generation in backend context is still whacky.
I had my constants at the wrong template.

I've tested a lot, simplified and (hopefully) fixed the TS generation a little. Should work much better now and even should allow multiple blog within one installation (something that could be an issue when coming to backend email sending; never tested this though).

Please checkout latest master and test in your setup. Please give feedback how your TS (and constants) setup looks like (where is the static ts, where the constants if used, where is your own TS, ...)

Hint: when changing the TS it's important to update the backend TS by using 
````
module.tx_t3extblog < plugin.tx_t3extblog
````

@pvanhemmen 
Experiencing #51 issue within the emails in my Introduction Package installation as well as in my private installation. No idea why.

**Comment by fnagel** [comment]
> Here's another one: 

Fixed!

**Comment by fnagel** [comment]
There are still some issues with link generation in BE context.

6.2 and 7.4 are totally different when coming to TS processing in BE. Totally inconsistent and hard to understand. It's a mess and I'm on it.

**Comment by fnagel** [comment]
Ok, link generation in BE is now fixed for 6.2 and 7.4

Please test and give feedback.

**Comment by criwe** [comment]
Sorry for the late reply. If´ve installed t3extblog on a live system now.

@fnagel: the language/comment problem didn´t occur there.

But I´ve noticed some other issues:

- Rss: No articles to see there. In the source code everythings there. The RSS-Validator shows some errors. I do not use RealURL, maybe I works with? 
- Sender-email is not user when emails are send to a subscriber. Admin-mail: it works.
- BE: No comments anymore. Comments the need to be approved are shown as long as they aren´t approved.

TYPO3 6.2.14

**Comment by fnagel** [comment]
@criwe 

1) 
I would need more specific data on this issue. For what I can see atm this works as expected: http://www.felixnagel.com/blog/rss-feed/ Perhaps there are some encoding issues? RealUrl could be a reason...

2) 
> Sender-email is not user when emails are send to a subscriber

Right, sender email (email from) should not be the users email as this would lead to issues on some servers. I do not see any reason to receive an opt-in email from my own email address. This behavior of t3extblog has not changed at all.

3) I'm not able to reproduce this, neither in the t3extblog module nor in list module. Did you check your TS on that page with template object browser?

**Comment by criwe** [comment]
@fnagel 
1) I´ve installed realurl, rss works fine now. I´ll deinstall it and email you the link to the none-working rss (without realurl). 
2) Oh, I meant "subscriber.mailFrom.email". This should be the sender-email-address when a subscriber gets an "new comment"-Email?
3.) Jep, TS looks fine. I´ve cleared the cache via installtool too, but still the same behaviour... in the list-view, all comments are shown

**Comment by fnagel** [comment]
@criwe 

1) Yes, it's the non-realurl links which break the RSS spec. I will add a notice in the doc as I don't think anyone uses t3extblog without RealUrl.

2) Correct, ````subscriptionManager.subscriber.mailFrom.email```` is the send from email address for subscriber notify email. Are you sure you TS is correct? There is a new constant using this TS setting by default.

3) Any message? Does ````module.tx_t3extblog.persistence.storagePid```` has a value? Otherwise this still sounds like missing TS config :-/

**Comment by pvanhemmen** [comment]
I've been integrating t3extblog to test it within a staging environment and it has been pretty stable so far. Two things that I noticed:

1. Comments in the BE from within the Manager don't seem to work anymore.
![comments-three](https://cloud.githubusercontent.com/assets/715022/9836016/7396a9d0-5a08-11e5-9874-24396207fefe.png)

And in the Post overview section:
![comments-two](https://cloud.githubusercontent.com/assets/715022/9836017/79af0bc8-5a08-11e5-9421-7c087643375e.png)

From within list view, everythings's there. Also comments and comment counts are displayed correctly in the Frontend.
![comments-one](https://cloud.githubusercontent.com/assets/715022/9836019/8789869c-5a08-11e5-85a6-ec6352e48302.png)

2. Probably not 2.0.0. related. But Search Indexed Blog Posts always have a trailing slash appended at their title:
![search](https://cloud.githubusercontent.com/assets/715022/9836022/b947b910-5a08-11e5-9e07-3a13d58ac9b3.png)

Hope that helps!

**Comment by fnagel** [comment]
@pvanhemmen 

1) 
I'm not able to reproduce this. Looks good in my installation.
![screenshot-2 png](https://cloud.githubusercontent.com/assets/116824/9838992/9a780e5e-5a6c-11e5-8f40-857b54b1d2a2.png)
![screenshot-2 png 1](https://cloud.githubusercontent.com/assets/116824/9838993/9a7a9c32-5a6c-11e5-992d-fb3e12dd60d6.png)

Did you check if the TS (´´´´persistence.storagePid´´´´) is available (via TS object browser) on that page?

2) I've opened a new ticket for this issue, see #85

**Comment by fnagel** [comment]
@criwe Any feedback on your issues? Please see https://github.com/fnagel/t3extblog/issues/79#issuecomment-135200757

**Comment by criwe** [comment]
@fnagel:  module.tx_t3extblog.persistence.storagePid = 123 fixed the problem (#79 (comment). You need to set 
plugin.tx_t3extblog.persistence.storagePid = 123 AND module.tx_t3extblog.persistence.storagePid = 123 to get all running. I´ll make a remind for the documentation.

**Comment by fnagel** [comment]
@criwe So all your above mentioned issues are solved?

**Comment by criwe** [comment]
@fnagel still got problems with the sendermailadress, both settings do not work in my installations:

plugin.tx_t3extblog.settings.subscriptionManager.subscriber.mailFrom.email = subscriberfrom@mail.tld
module.tx_t3extblog.settings.subscriptionManager.subscriber.mailFrom.email = modulemail@mail.tld

for the adminmail, it works. Mails to the subscriber (subscribing notification or messege for new comments) are always sent from the mailadress i´ve set via installtool.

But maybe a issue of my installation?

**Comment by fnagel** [comment]
@criwe Please test latest commit. There was a bug (seems like a pretty old one) in email address setting which had nothing to do with TS beeing available. Should be fixed by now.

**Comment by fnagel** [comment]
@criwe @pvanhemmen 

You both reported issues with displaying comments in BE module. This should be fixed by now. Comments view used storagePid but should be using current page tree selection (see related commit 328ad1d00cc52d2d8284b90bdce185d89a974910).

I've added some checks for validating proper TS settings (throws expection if not available, see this commit: c6784c76f2643d72416951fce2bd61ca4dd78e72)

Another improvement is a flash notice if no proper blog page is used in BE module page tree (related commit: 6dd8d8ce4c2d9f2316d5e5c3500be7c4f285153c)

Hope you guys like it!

**Comment by pvanhemmen** [comment]
The comments issue is sorted out and works for me. Marked as done. Great work, thank you!

**Comment by criwe** [comment]
@fnagel the newst code fixed the Problem: https://github.com/fnagel/t3extblog/issues/79#issuecomment-142372601). The other improvements (https://github.com/fnagel/t3extblog/issues/79#issuecomment-142523991) worked fine too. Great job!

**Comment by fnagel** [comment]
Thanks for the feedback. I think we're almost good to go!

I think we should wait for TYPO3 7.5 and test t3extblog for this version too *sigh*. We need to update the docs anyway before we could release version 2.0.0.

**Comment by pvanhemmen** [comment]
Did a short test in 7.5 and have found one issue. Registering Icons with
```'iconfile' => \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extRelPath($_EXTKEY) . 'Resources/Public/Icons/page.png```
in `ext_tables.php` does not work anymore and generates an invalid relative link to the Icon. Using the EXT: Prefix icon paths are correct again:
```'iconfile' => 'EXT:t3extblog/Resources/Public/Icons/page.png'```

Other than that everything seems to work fine at first sight.

**Comment by pvanhemmen** [comment]
The new Fluid Styled CE in 7.5 seem to work without any problems when used within posts. Looks like a very smooth migration, which is awesome.

**Comment by fnagel** [comment]
Icon registering is fixed in latest master. 

This TCA field change seems a little disturbing to me. Any idea?
![tca_change](https://cloud.githubusercontent.com/assets/116824/10265255/3ec1b4c6-6a29-11e5-8867-a503b1d62e86.png)

**Comment by pvanhemmen** [comment]
@fnagel Have a look at https://docs.typo3.org/typo3cms/TCAReference/Reference/Columns/Select/Index.html#noiconsbelowselect. This will disable the icon display below selects. In short, adding a `'noIconsBelowSelect' => true,` to the select config of `l18n_parent` will hide the icons. Hope that helps!

**Comment by fnagel** [comment]
@pvanhemmen Thanks for the hint. Added for better usability.

**Comment by fnagel** [comment]
Another thing I've noticed: The displayCond for the l18n_parent field seems not to work anymore, not only in t3extblog but for all CEs (for example tt_content). The parent localization field (German: "Ursprungstext") is always displayed, even in single language installations. Any idea why this was changed in TYPO3 7.5?

**Comment by pvanhemmen** [comment]
displayCond problems Confirmed. I can't find anything in the changelogs regarding a change. Changing the condition to `'displayCond' => 'FIELD:sys_language_uid:!=:0'` works. Seems like a bug on first sight.

**Comment by fnagel** [comment]
Closing this ticket for now. Please continue here #89
